runtime: custom
env: flex
service: nestjs-books
automatic_scaling:
  min_num_instances: 1
network:
  forwarded_ports:
    - 80
  session_affinity: true   
beta_settings:
  cloud_sql_instances: techedge-es-bp-dyn-dsup-dev:europe-west1:books=tcp:3306