branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: CircleCI-Books
  branch: null
  default_ec2_keyname: CircleCIKeyPair
  default_platform: docker
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
