# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

executors:
  my-executor:
    docker:
      - image: lakoo/node-gcloud-docker
    working_directory: /tmp/books

jobs:
  build:
    executor: my-executor

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      # - run: curl -sL https://deb.nodesource.com/setup_6.x | bash -
      # - run: apt-get install -y nodejs
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ./
          paths:
            - ./*

  test:
    executor: my-executor
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/books
      - run: npm test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

  authorize:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp/books
      - run: | 
          docker login -u _json_key -p $GCLOUD_SERVICE_KEY https://eu.gcr.io        
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account techedge-es-bp-dyn-dsup-dev@appspot.gserviceaccount.com --key-file=
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
  deploy:
    executor: my-executor
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/books
      - run:
          name: Deploy Master to GKE
          command: ./deploy.sh
workflows:
  version: 2
  build_and_test: # name of your workflow
    jobs:
      - build
      - test:
          requires:
            - build
      - authorize:
          requires:
            - test
      - deploy:
          requires:
            - authorize
